import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import { ScrollToTopButton } from '@/components/shared/ScrollToTop';
import { ThemeProvider } from '@/components/providers/theme-provider';
import AppClerkProvider from '@/components/providers/ClerkProvider';
import { Toaster } from '@/components/ui/toaster';
import QueryProvider from '@/components/shared/providers/QueryProvider';

const geistSans = Ubuntu({
    weight: '700',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Task Flow',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans} antialiased`}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppClerkProvider>
                        <QueryProvider>
                            {children}
                            <ScrollToTopButton />
                            <Toaster />
                        </QueryProvider>
                    </AppClerkProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
