import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/shared/Navigation";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ScrollToTop from "@/components/shared/ScrollToTop";

const ubuntu = Ubuntu({
  weight: "500",
  subsets: ["latin-ext"]
});

export const metadata: Metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntu.className} antialiased min-h-screen bg-background`}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            <Navigation />
            {children}
            <ScrollToTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
