import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import { ScrollToTopButton } from '@/components/shared/ScrollToTop';
import { ThemeProvider } from '@/components/providers/theme-provider';
import AppClerkProvider from '@/components/providers/ClerkProvider';

const geistSans = Ubuntu({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Task Flow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <AppClerkProvider>
            {children}
            <ScrollToTopButton />
          </AppClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
